import type { Quarter } from '../types';
const raw = [
  [
    'Fall 2026',
    'The Wake-Up Call',
    'Build the first repeatable day.',
    [
      'Baseline finances, time, health, academics, and projects',
      'Create a personal operating system',
      'Clarify the portfolio and conduct discovery',
    ],
    [
      'Net worth versus cash',
      'Opportunity cost',
      'Git and GitHub fundamentals',
    ],
    'The Overcommitment Trap',
    '2026 Vision Contract and Project Portfolio Map',
    'The bedside journal appears.',
  ],
  [
    'Spring 2027',
    'Proof Before Prestige',
    'Listen before claiming the title.',
    [
      'Interview learners and users',
      'Prototype the literacy course and Atlas alpha',
      'Set research and privacy principles',
    ],
    [
      'Customer discovery',
      'Minimum viable products',
      'Consent and data privacy',
    ],
    'The First Real Sales Conversation',
    'Pilot Results and Evidence Report',
    'A capable CEO runs the stand-up.',
  ],
  [
    'Summer 2027',
    'First Cash Flow',
    'One clear offer earns its first yes.',
    [
      'Create a repeatable offer',
      'Build a simple funnel',
      'Practice bookkeeping and cash discipline',
    ],
    [
      'Revenue, margin, expense, and profit',
      'Cash flow and runway',
      'Intellectual property basics',
    ],
    'Revenue Is Not Profit',
    'First Cash-Flow Playbook',
    'The $20 million screen separates liquid and illiquid assets.',
  ],
  [
    'Fall 2027',
    'Systems Become Freedom',
    'Make good work repeatable.',
    [
      'Document recurring processes',
      'Protect doctoral research time',
      'Delegate and strengthen security',
    ],
    [
      'SOPs and quality control',
      'Delegation and KPIs',
      'MFA, backups, and recovery',
    ],
    'The Founder Bottleneck',
    'McGaffie Operating System, Version 1',
    'Marcus appears as time leverage, not status.',
  ],
  [
    'Spring 2028',
    'Evidence and Credibility',
    'Confidence rests on evidence.',
    [
      'Advance dissertation research',
      'Validate BREXAtlas',
      'Build careful partnerships',
    ],
    ['Research design', 'Reproducibility', 'Evidence-based pitching'],
    'The Temptation to Overclaim',
    'Evidence Dossier',
    'Diligence interrupts excitement.',
  ],
  [
    'Summer 2028',
    'Doctor to Founder',
    'Translate scholarship into public value.',
    [
      'Complete the doctoral milestone',
      'Publish a research brief',
      'Deliver a flagship talk',
    ],
    [
      'Academic-to-market translation',
      'Ethical personal branding',
      'Rest after milestones',
    ],
    'The Identity Gap',
    'Doctoral Legacy Portfolio',
    'The keynote audience becomes visible.',
  ],
  [
    'Fall 2028',
    'The Company, Not the Hustle',
    'Build an organization that delivers.',
    [
      'Formalize the business model',
      'Improve recurring revenue',
      'Establish governance foundations',
    ],
    [
      'Unit economics',
      'Cap tables and ownership',
      'Management versus ownership',
    ],
    'The Hero-Founder Habit',
    'Company Operating Charter',
    'Three questions empower the executive team.',
  ],
  [
    'Spring 2029',
    'The Atlas Network',
    'Build a coherent research-intelligence ecosystem.',
    [
      'Integrate Atlas products',
      'Clarify data rights',
      'Develop institutional partnerships',
    ],
    ['Platform strategy', 'Privacy by design', 'Data provenance'],
    'The Data-Moat Illusion',
    'Atlas Ecosystem Blueprint',
    'The lab traces evidence and discovery pathways.',
  ],
  [
    'Summer 2029',
    'Capital With a Purpose',
    'Choose capital for strategy, not status.',
    [
      'Choose a capital path',
      'Understand dilution',
      'Establish a giving philosophy',
    ],
    [
      'Bootstrapping and grants',
      'Term sheets and dilution',
      'Capital allocation',
    ],
    'Vanity Capital',
    'Capital and Stewardship Plan',
    'Students enter a future literacy lab.',
  ],
  [
    'Fall 2029',
    'Build, Buy, or Partner',
    'Buying growth can create or destroy value.',
    [
      'Create an acquisition thesis',
      'Practice diligence',
      'Design integration plans',
    ],
    ['Strategic fit', 'Quality of earnings', 'The first 100 days'],
    'The Shiny Acquisition',
    'Build-Buy-Partner Decision Book',
    'The acquisition review is disciplined.',
  ],
  [
    'Spring 2030',
    'Influence at Scale',
    'Influence moves people toward ethical action.',
    [
      'Build a keynote platform',
      'Form an advisory council',
      'Prepare for scrutiny',
    ],
    ['Executive storytelling', 'Board communication', 'Crisis response'],
    'The Applause Trap',
    'Influence and Communication System',
    'The camera asks what responsibility follows attention.',
  ],
  [
    'Summer 2030',
    'Protect What You Built',
    'Protection is a coordinated professional process.',
    [
      'Draft an investment policy',
      'Map the advisory team',
      'Review continuity and privacy',
    ],
    [
      'Diversification and liquidity',
      'Securities-backed lending risks',
      'Estate-planning questions',
    ],
    'Paper Wealth, Real Risk',
    'Protection and Continuity Binder',
    'The estate reveals governance and maintenance.',
  ],
  [
    'Fall 2030',
    'Global and Multi-Company',
    'Operate responsibly across markets.',
    [
      'Evaluate international markets',
      'Design a multi-company map',
      'Build a global research network',
    ],
    ['Market entry', 'Currency and localization risk', 'Cultural intelligence'],
    'Expansion Without Understanding',
    'Global Enterprise Map',
    'Travel becomes infrastructure for relationships.',
  ],
  [
    'Spring 2031',
    'Owner, Steward, Chairman',
    'Leave operation without abandoning responsibility.',
    [
      'Develop CEO succession',
      'Define a chairman calendar',
      'Establish family governance',
    ],
    ['CEO succession', 'Family governance', 'Philanthropic strategy'],
    'Control Disguised as Responsibility',
    'Chairman and Family Stewardship Charter',
    'Did I transfer wisdom, or only assets?',
  ],
  [
    'Summer 2031',
    'Vision Day',
    'See the systems beneath the spectacle.',
    [
      'Integrate the journey',
      'Review the $20 million architecture',
      'Draft the next ten-year vision',
    ],
    [
      'Liquidity versus valuation',
      'Sustainable lifestyle math',
      'Time freedom',
    ],
    'The Board of the Future Self',
    'The 2031 McGaffie Legacy Letter',
    'La visión ya existe — ahora camínala.',
  ],
] as const;
const starts = [
  '2026-09-01',
  '2027-01-01',
  '2027-05-01',
  '2027-09-01',
  '2028-01-01',
  '2028-05-01',
  '2028-09-01',
  '2029-01-01',
  '2029-05-01',
  '2029-09-01',
  '2030-01-01',
  '2030-05-01',
  '2030-09-01',
  '2031-01-01',
  '2031-05-01',
];
const ends = [
  '2026-12-31',
  '2027-04-30',
  '2027-08-31',
  '2027-12-31',
  '2028-04-30',
  '2028-08-31',
  '2028-12-31',
  '2029-04-30',
  '2029-08-31',
  '2029-12-31',
  '2030-04-30',
  '2030-08-31',
  '2030-12-31',
  '2031-04-30',
  '2031-08-31',
];
export const quarters: Quarter[] = raw.map((r, i) => ({
  id: i + 1,
  season: r[0],
  title: r[1],
  story: r[2],
  goals: [...r[3]],
  lessons: [...r[4]],
  boss: r[5],
  artifact: r[6],
  echo: r[7],
  start: starts[i],
  end: ends[i],
  milestones: [
    `Complete the ${r[1]} baseline`,
    `Create evidence for ${r[6]}`,
    'Review tradeoffs and next actions',
  ],
}));
