import type { Source } from '../types';
const defs = [
  [
    'fdic-deposit',
    'Deposit Insurance At A Glance',
    'FDIC',
    'finance',
    'https://www.fdic.gov/resources/deposit-insurance/',
  ],
  [
    'treasury-bills',
    'Treasury Bills',
    'U.S. Treasury',
    'investing',
    'https://www.treasurydirect.gov/marketable-securities/treasury-bills/',
  ],
  [
    'sec-diversification',
    'Diversification',
    'Investor.gov',
    'investing',
    'https://www.investor.gov/introduction-investing/investing-basics/glossary/diversification',
  ],
  [
    'finra-sbloc',
    'Securities-Backed Lines of Credit',
    'FINRA',
    'risk',
    'https://www.finra.org/investors/insights/securities-backed-lines-credit',
  ],
  [
    'sba-plan',
    'Write Your Business Plan',
    'U.S. Small Business Administration',
    'business',
    'https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan',
  ],
  [
    'nist-csf',
    'Cybersecurity Framework 2.0',
    'NIST',
    'security',
    'https://www.nist.gov/cyberframework',
  ],
  [
    'cisa-mfa',
    'More than a Password',
    'CISA',
    'security',
    'https://www.cisa.gov/secure-our-world/use-strong-passwords',
  ],
  [
    'ohrp',
    'Human Research Protections',
    'HHS OHRP',
    'research',
    'https://www.hhs.gov/ohrp/',
  ],
  [
    'sec-ipo',
    'Going Public',
    'SEC',
    'ipo',
    'https://www.sec.gov/education/capitalraising/goingpublic',
  ],
  [
    'irs-foundation',
    'Private Foundations',
    'IRS',
    'philanthropy',
    'https://www.irs.gov/charities-non-profits/charitable-organizations/private-foundations',
  ],
  [
    'ftc-phishing',
    'How to Recognize and Avoid Phishing Scams',
    'FTC',
    'security',
    'https://consumer.ftc.gov/articles/how-recognize-and-avoid-phishing-scams',
  ],
  [
    'uspto-ip',
    'IP Basics',
    'USPTO',
    'business',
    'https://www.uspto.gov/learning-and-resources/ip-policy/intellectual-property-basics',
  ],
  [
    'faa-charter',
    'Charter Aviation',
    'FAA',
    'aviation',
    'https://www.faa.gov/about/initiatives/safecharteroperations',
  ],
  [
    'cfpb-budget',
    'Budgeting',
    'Consumer Financial Protection Bureau',
    'finance',
    'https://www.consumerfinance.gov/consumer-tools/budgeting/',
  ],
  [
    'nih-rigor',
    'Rigor and Reproducibility',
    'NIH',
    'research',
    'https://www.nih.gov/research-training/rigor-reproducibility',
  ],
] as const;
export const sources: Source[] = defs.map((x, i) => ({
  id: x[0],
  title: x[1],
  organization: x[2],
  category: x[3],
  url: x[4],
  reviewed: '2026-07-11',
  lessonIds: Array.from({ length: 4 }, (_, j) => `lesson-${i * 4 + j + 1}`),
}));
